repositories {
    mavenCentral()
    google() // Needed for androidx
    maven { url = 'https://maven.brott.dev/' }
}

dependencies {
    implementation 'org.firstinspires.ftc:Inspection:11.2.0'
    implementation 'org.firstinspires.ftc:Blocks:11.2.0'
    implementation 'org.firstinspires.ftc:RobotCore:11.2.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.2.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.2.0'
    implementation 'org.firstinspires.ftc:Hardware:11.2.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.2.0'
    implementation 'org.firstinspires.ftc:Vision:11.2.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.acmerobotics.dashboard:dashboard:0.6.0'
}

