package org.firstinspires.ftc.teamcode.helpers;

public enum GameState {
    SCAN_INITIAL,
    SCAN_SECONDARY,
    DRIVE_TO_CAROUSEL_ONE,
    DRIVE_TO_CAROUSEL_TWO,
    DRIVE_TO_CAROUSEL_THREE,
    SPIN_CAROUSEL,
    DRIVE_TO_ALLIANCE_HUB_ONE,
    DRIVE_TO_ALLIANCE_HUB_ONE_PRIMARY,
    DRIVE_TO_ALLIANCE_HUB_ONE_SECONDARY,
    ROTATE_TURNTABLE,
    DRIVE_TO_ALLIANCE_HUB_TWO,
    PLACE_CUBE,
    PARK_IN_BOTTOM_WAREHOUSE,
    PARK_IN_TOP_WAREHOUSE_ONE,
    PARK_IN_TOP_WAREHOUSE_TWO,
    COMPLETE;
}