package org.firstinspires.ftc.teamcode.ultimategoal2020.opmodes.autonstates;

@Deprecated
public enum AutonStateEnum {
    CONFIGURE_AUTON_ROUTINE,
    PREMATCH_SETUP,
    DETECT_STARTER_STACK,
    INITIALIZE,
    UNFOLD_CRANE,
    GRAB_FIRST_WOBBLE_GOAL,
    MOVE_TO_TARGET_ZONE,
    PLACE_WOBBLE_GOAL,
    MOVE_TO_LAUNCH_LINE,
    SHOOT_POWER_SHOTS,
    MOVE_TO_SECOND_START_LINE,
    PICKUP_SECOND_WOBBLE_GOAL,
    MOVE_TO_TARGET_ZONE_AGAIN,
    PARK_ON_LAUNCH_LINE,
    COMPLETED,

    //********  THE FOLLOWING STATES ARE UTILITY STATES *********,
    SET_PID_COEFFICIENTS,
    MOVE_FOR_CALIBRATION,
    AWAIT_USER_FEEDBACK,
    SPIN_360_DEGREES,
    TEST_CONTROL_LOOP_SPEED

}
