package org.firstinspires.ftc.Team19567.util;

public enum AUTO_STATE {
    DETECTING_OPENCV,
    MOVING_TO_HUB,
    MOVING_TO_WAREHOUSE,
    MOVING_TO_CAROUSEL,
    INTAKING_FREIGHT,
    RETURNING_TO_HUB,
    ROTATING_CAROUSEL,
    PARKING_UNIT,
    PARING_WAREHOUSE,
    DELIVERING_FREIGHT,
    PATH_FINISHED
}