node {
  name: "x"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/Conv1_pad/Pad"
  op: "Pad"
  input: "x"
  input: "sequential_4/sequential_1/model1/Conv1_pad/Pad/paddings"
}
node {
  name: "sequential_4/sequential_1/model1/Conv1/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/Conv1_pad/Pad"
  input: "sequential_4/sequential_1/model1/Conv1/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/bn_Conv1/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/Conv1/Conv2D"
  input: "sequential_4/sequential_1/model1/bn_Conv1/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/bn_Conv1/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/bn_Conv1/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/bn_Conv1/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/Conv1_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/bn_Conv1/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/expanded_conv_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/Conv1_relu/Relu6"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/expanded_conv_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/expanded_conv_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/expanded_conv_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/expanded_conv_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/expanded_conv_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/expanded_conv_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/expanded_conv_project/Conv2D"
  input: "sequential_4/sequential_1/model1/expanded_conv_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/expanded_conv_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/expanded_conv_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/expanded_conv_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_1_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/expanded_conv_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_1_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_1_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_1_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_1_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_1_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_1_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_1_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_1_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_1_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_1_pad/Pad"
  op: "Pad"
  input: "sequential_4/sequential_1/model1/block_1_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_1_pad/Pad/paddings"
}
node {
  name: "sequential_4/sequential_1/model1/block_1_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_1_pad/Pad"
  input: "sequential_4/sequential_1/model1/block_1_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_1_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_1_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_1_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_1_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_1_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_1_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_1_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_1_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_1_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_1_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_1_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_1_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_1_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_1_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_1_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_1_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_1_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_2_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_1_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_2_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_2_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_2_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_2_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_2_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_2_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_2_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_2_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_2_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_2_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_2_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_2_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_2_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_2_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_2_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_2_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_2_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_2_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_2_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_2_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_2_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_2_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_2_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_2_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_2_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_2_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_2_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_2_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_2_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_2_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_1_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_2_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_3_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_2_add/add"
  input: "sequential_4/sequential_1/model1/block_3_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_3_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_3_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_3_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_3_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_3_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_3_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_3_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_3_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_3_pad/Pad"
  op: "Pad"
  input: "sequential_4/sequential_1/model1/block_3_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_3_pad/Pad/paddings"
}
node {
  name: "sequential_4/sequential_1/model1/block_3_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_3_pad/Pad"
  input: "sequential_4/sequential_1/model1/block_3_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_3_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_3_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_3_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_3_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_3_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_3_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_3_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_3_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_3_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_3_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_3_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_3_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_3_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_3_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_3_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_3_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_3_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_4_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_3_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_4_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_4_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_4_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_4_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_4_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_4_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_4_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_4_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_4_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_4_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_4_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_4_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_4_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_4_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_4_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_4_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_4_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_4_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_4_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_4_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_4_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_4_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_4_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_4_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_4_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_4_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_4_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_4_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_4_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_4_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_3_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_4_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_5_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_4_add/add"
  input: "sequential_4/sequential_1/model1/block_5_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_5_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_5_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_5_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_5_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_5_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_5_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_5_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_5_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_5_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_5_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_5_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_5_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_5_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_5_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_5_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_5_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_5_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_5_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_5_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_5_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_5_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_5_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_5_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_5_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_5_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_5_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_5_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_5_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_5_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_4_add/add"
  input: "sequential_4/sequential_1/model1/block_5_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_6_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_5_add/add"
  input: "sequential_4/sequential_1/model1/block_6_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_6_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_6_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_6_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_6_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_6_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_6_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_6_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_6_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_6_pad/Pad"
  op: "Pad"
  input: "sequential_4/sequential_1/model1/block_6_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_6_pad/Pad/paddings"
}
node {
  name: "sequential_4/sequential_1/model1/block_6_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_6_pad/Pad"
  input: "sequential_4/sequential_1/model1/block_6_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_6_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_6_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_6_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_6_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_6_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_6_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_6_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_6_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_6_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_6_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_6_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_6_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_6_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_6_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_6_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_6_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_6_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_7_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_6_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_7_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_7_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_7_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_7_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_7_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_7_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_7_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_7_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_7_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_7_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_7_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_7_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_7_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_7_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_7_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_7_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_7_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_7_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_7_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_7_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_7_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_7_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_7_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_7_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_7_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_7_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_7_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_7_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_7_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_7_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_6_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_7_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_8_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_7_add/add"
  input: "sequential_4/sequential_1/model1/block_8_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_8_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_8_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_8_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_8_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_8_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_8_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_8_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_8_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_8_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_8_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_8_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_8_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_8_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_8_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_8_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_8_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_8_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_8_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_8_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_8_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_8_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_8_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_8_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_8_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_8_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_8_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_8_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_8_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_8_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_7_add/add"
  input: "sequential_4/sequential_1/model1/block_8_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_9_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_8_add/add"
  input: "sequential_4/sequential_1/model1/block_9_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_9_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_9_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_9_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_9_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_9_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_9_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_9_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_9_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_9_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_9_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_9_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_9_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_9_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_9_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_9_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_9_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_9_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_9_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_9_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_9_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_9_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_9_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_9_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_9_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_9_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_9_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_9_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_9_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_9_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_8_add/add"
  input: "sequential_4/sequential_1/model1/block_9_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_10_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_9_add/add"
  input: "sequential_4/sequential_1/model1/block_10_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_10_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_10_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_10_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_10_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_10_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_10_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_10_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_10_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_10_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_10_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_10_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_10_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_10_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_10_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_10_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_10_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_10_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_10_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_10_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_10_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_10_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_10_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_10_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_10_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_10_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_10_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_10_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_10_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_11_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_10_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_11_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_11_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_11_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_11_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_11_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_11_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_11_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_11_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_11_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_11_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_11_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_11_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_11_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_11_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_11_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_11_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_11_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_11_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_11_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_11_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_11_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_11_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_11_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_11_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_11_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_11_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_11_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_11_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_11_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_11_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_10_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_11_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_12_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_11_add/add"
  input: "sequential_4/sequential_1/model1/block_12_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_12_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_12_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_12_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_12_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_12_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_12_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_12_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_12_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_12_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_12_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_12_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_12_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_12_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_12_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_12_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_12_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_12_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_12_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_12_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_12_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_12_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_12_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_12_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_12_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_12_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_12_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_12_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_12_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_12_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_11_add/add"
  input: "sequential_4/sequential_1/model1/block_12_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_13_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_12_add/add"
  input: "sequential_4/sequential_1/model1/block_13_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_13_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_13_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_13_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_13_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_13_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_13_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_13_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_13_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_13_pad/Pad"
  op: "Pad"
  input: "sequential_4/sequential_1/model1/block_13_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_13_pad/Pad/paddings"
}
node {
  name: "sequential_4/sequential_1/model1/block_13_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_13_pad/Pad"
  input: "sequential_4/sequential_1/model1/block_13_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_13_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_13_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_13_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_13_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_13_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_13_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_13_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_13_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_13_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_13_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_13_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_13_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_13_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_13_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_13_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_13_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_13_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_14_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_13_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_14_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_14_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_14_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_14_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_14_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_14_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_14_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_14_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_14_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_14_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_14_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_14_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_14_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_14_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_14_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_14_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_14_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_14_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_14_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_14_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_14_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_14_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_14_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_14_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_14_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_14_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_14_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_14_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_14_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_14_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_13_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_14_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_15_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_14_add/add"
  input: "sequential_4/sequential_1/model1/block_15_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_15_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_15_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_15_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_15_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_15_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_15_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_15_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_15_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_15_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_15_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_15_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_15_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_15_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_15_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_15_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_15_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_15_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_15_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_15_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_15_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_15_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_15_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_15_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_15_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_15_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_15_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_15_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_15_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_15_add/add"
  op: "AddV2"
  input: "sequential_4/sequential_1/model1/block_14_add/add"
  input: "sequential_4/sequential_1/model1/block_15_project_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_16_expand/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_15_add/add"
  input: "sequential_4/sequential_1/model1/block_16_expand/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_16_expand_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_16_expand/Conv2D"
  input: "sequential_4/sequential_1/model1/block_16_expand_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_16_expand_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_16_expand_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_16_expand_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_16_expand_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_16_expand_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_16_depthwise/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential_4/sequential_1/model1/block_16_expand_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_16_depthwise/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_16_depthwise_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_16_depthwise/depthwise"
  input: "sequential_4/sequential_1/model1/block_16_depthwise_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_16_depthwise_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_16_depthwise_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_16_depthwise_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_16_depthwise_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/block_16_depthwise_BN/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/model1/block_16_project/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_16_depthwise_relu/Relu6"
  input: "sequential_4/sequential_1/model1/block_16_project/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/block_16_project_BN/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/block_16_project/Conv2D"
  input: "sequential_4/sequential_1/model1/block_16_project_BN/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_16_project_BN/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/block_16_project_BN/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/block_16_project_BN/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/Conv_1/Conv2D"
  op: "Conv2D"
  input: "sequential_4/sequential_1/model1/block_16_project_BN/FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/Conv_1/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/Conv_1_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential_4/sequential_1/model1/Conv_1/Conv2D"
  input: "sequential_4/sequential_1/model1/Conv_1_bn/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/Conv_1_bn/ReadVariableOp_1/resource"
  input: "sequential_4/sequential_1/model1/Conv_1_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential_4/sequential_1/model1/Conv_1_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential_4/sequential_1/model1/out_relu/Relu6"
  op: "Relu6"
  input: "sequential_4/sequential_1/model1/Conv_1_bn/FusedBatchNormV3"
}
node {
  name: "sequential_4/sequential_1/global_average_pooling2d_GlobalAveragePooling2D1/Mean"
  op: "Mean"
  input: "sequential_4/sequential_1/model1/out_relu/Relu6"
  input: "sequential_4/sequential_1/global_average_pooling2d_GlobalAveragePooling2D1/Mean/reduction_indices"
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
node {
  name: "sequential_4/sequential_3/dense_Dense1/MatMul"
  op: "MatMul"
  input: "sequential_4/sequential_1/global_average_pooling2d_GlobalAveragePooling2D1/Mean"
  input: "sequential_4/sequential_3/dense_Dense1/MatMul/ReadVariableOp/resource"
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "sequential_4/sequential_3/dense_Dense1/BiasAdd"
  op: "BiasAdd"
  input: "sequential_4/sequential_3/dense_Dense1/MatMul"
  input: "sequential_4/sequential_3/dense_Dense1/BiasAdd/ReadVariableOp/resource"
}
node {
  name: "sequential_4/sequential_3/dense_Dense1/Relu"
  op: "Relu"
  input: "sequential_4/sequential_3/dense_Dense1/BiasAdd"
}
node {
  name: "sequential_4/sequential_3/dense_Dense2/MatMul"
  op: "MatMul"
  input: "sequential_4/sequential_3/dense_Dense1/Relu"
  input: "sequential_4/sequential_3/dense_Dense2/MatMul/ReadVariableOp/resource"
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "sequential_4/sequential_3/dense_Dense2/Softmax"
  op: "Softmax"
  input: "sequential_4/sequential_3/dense_Dense2/MatMul"
}
node {
  name: "Identity"
  op: "Identity"
  input: "sequential_4/sequential_3/dense_Dense2/Softmax"
}
